# Automatically generated by "pub global run bazel:bazelify".
# DO NOT MODIFY BY HAND

PUB_PACKAGE_NAME = "vscode_polyglot"

# Generated automatically for package:vscode_polyglot|pubspec.yaml
def bazelify():
    native.new_local_repository(
        name = "analyzer",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/analyzer-0.29.2/",
        build_file = ".bazelify/analyzer.BUILD",
    )
    native.new_local_repository(
        name = "args",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/args-0.13.7/",
        build_file = ".bazelify/args.BUILD",
    )
    native.new_local_repository(
        name = "async",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/async-1.11.3/",
        build_file = ".bazelify/async.BUILD",
    )
    native.new_local_repository(
        name = "barback",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/barback-0.15.2+9/",
        build_file = ".bazelify/barback.BUILD",
    )
    native.new_local_repository(
        name = "charcode",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.1/",
        build_file = ".bazelify/charcode.BUILD",
    )
    native.new_local_repository(
        name = "code_builder",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/code_builder-1.0.0-alpha+7/",
        build_file = ".bazelify/code_builder.BUILD",
    )
    native.new_local_repository(
        name = "collection",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/collection-1.12.0/",
        build_file = ".bazelify/collection.BUILD",
    )
    native.new_local_repository(
        name = "convert",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/convert-2.0.1/",
        build_file = ".bazelify/convert.BUILD",
    )
    native.new_local_repository(
        name = "crypto",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/crypto-2.0.1/",
        build_file = ".bazelify/crypto.BUILD",
    )
    native.new_local_repository(
        name = "csslib",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/csslib-0.13.2+2/",
        build_file = ".bazelify/csslib.BUILD",
    )
    native.new_local_repository(
        name = "dart_style",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/dart_style-0.2.13/",
        build_file = ".bazelify/dart_style.BUILD",
    )
    native.new_local_repository(
        name = "glob",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/glob-1.1.3/",
        build_file = ".bazelify/glob.BUILD",
    )
    native.new_local_repository(
        name = "html",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/html-0.13.1/",
        build_file = ".bazelify/html.BUILD",
    )
    native.new_local_repository(
        name = "isolate",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/isolate-0.2.3/",
        build_file = ".bazelify/isolate.BUILD",
    )
    native.new_local_repository(
        name = "js",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/js-0.6.1/",
        build_file = ".bazelify/js.BUILD",
    )
    native.new_local_repository(
        name = "logging",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/logging-0.11.3+1/",
        build_file = ".bazelify/logging.BUILD",
    )
    native.new_local_repository(
        name = "matcher",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/matcher-0.12.0+2/",
        build_file = ".bazelify/matcher.BUILD",
    )
    native.new_local_repository(
        name = "meta",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/meta-1.0.4/",
        build_file = ".bazelify/meta.BUILD",
    )
    native.new_local_repository(
        name = "package_config",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/package_config-1.0.0/",
        build_file = ".bazelify/package_config.BUILD",
    )
    native.new_local_repository(
        name = "path",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/path-1.4.1/",
        build_file = ".bazelify/path.BUILD",
    )
    native.new_local_repository(
        name = "plugin",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/plugin-0.2.0/",
        build_file = ".bazelify/plugin.BUILD",
    )
    native.new_local_repository(
        name = "polyglot",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/polyglot-1.0.0-dev/",
        build_file = ".bazelify/polyglot.BUILD",
    )
    native.new_local_repository(
        name = "pool",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/pool-1.2.4/",
        build_file = ".bazelify/pool.BUILD",
    )
    native.new_local_repository(
        name = "source_span",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/source_span-1.3.0/",
        build_file = ".bazelify/source_span.BUILD",
    )
    native.new_local_repository(
        name = "stack_trace",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.7.0/",
        build_file = ".bazelify/stack_trace.BUILD",
    )
    native.new_local_repository(
        name = "string_scanner",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.1/",
        build_file = ".bazelify/string_scanner.BUILD",
    )
    native.new_local_repository(
        name = "typed_data",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/typed_data-1.1.3/",
        build_file = ".bazelify/typed_data.BUILD",
    )
    native.new_local_repository(
        name = "utf",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+3/",
        build_file = ".bazelify/utf.BUILD",
    )
    native.new_local_repository(
        name = "vscode",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/vscode-1.0.0/",
        build_file = ".bazelify/vscode.BUILD",
    )
    native.new_local_repository(
        name = "watcher",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.7+3/",
        build_file = ".bazelify/watcher.BUILD",
    )
    native.new_local_repository(
        name = "yaml",
        path = "/Users/tobe/.pub-cache/hosted/pub.dartlang.org/yaml-2.1.12/",
        build_file = ".bazelify/yaml.BUILD",
    )
    native.new_local_repository(
        name = "vscode_polyglot",
        path = "/Users/tobe/Source/Dart/vscode_polyglot/",
        build_file = ".bazelify/vscode_polyglot.BUILD",
    )
