author: "Tobe O <thosakwe@gmail.com>"
description: "VSCode support for ng2_polyglot."
homepage: "https://github.com/thosakwe/vscode_polyglot.git"
name: "vscode_polyglot"
version: "1.0.0-dev"
dependencies: 
  node_preamble: "^1.2.0"
  polyglot: "^1.0.0-dev"
  vscode: "^1.0.0"
dev_dependencies: 
  grinder: "^0.8.0+3"
