author: "Tobe O <thosakwe@gmail.com>"
description: "VSCode support for ng2_polyglot."
homepage: "https://github.com/thosakwe/vscode_polyglot.git"
name: "vscode_polyglot"
version: "1.0.0-dev"
dependencies: 
  polyglot: 
    path: "../ng2_polyglot"
  vscode: 
    path: "../dart_vscode"
