author: "Tobe O <thosakwe@gmail.com>"
description: "VSCode support for ng2_polyglot."
homepage: "https://github.com/thosakwe/vscode_polyglot.git"
name: "vscode_polyglot"
version: "1.0.0-dev"
dependencies: 
  barback: "^0.15.2+9"
  glob: "^1.1.3"
  node_preamble: "^1.2.0"
  polyglot: "^1.0.0-dev"
  vscode: "^1.0.0"
dev_dependencies: 
  grinder: "^0.8.0+3"
transformers:
- vscode_polyglot:
    glob: "**/*.json"
- vscode_polyglot:
    glob: "*.js"
- $dart2js:
    commandLineOptions: [-node=true]
- vscode_polyglot/add_preamble